name: CI Release 3.x

on:
  push:
    branches:
      - 'release-3.0'
    tags:
      - 'v3.*'
  pull_request:
    branches:
      - release-3.0
  schedule:
    - cron: '0 3 * * 3' # Wednesdays at 3am

env:
  CI: true
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ci-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ember

  test-build:
    name: Build Tests
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ci-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Test
        run: yarn test:build

  test-no-lock:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs: [test, test-build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ci-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --no-lockfile --non-interactive
      - name: Test
        run: yarn test:ember

  test-try:
    name: Scenario Tests
    runs-on: ubuntu-latest
    needs: [test, test-build, test-no-lock]
    strategy:
      fail-fast: false
      matrix:
        command:
          - ember test
        scenario:
          - ember-lts-2.18
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic
        include:
          - scenario: embroider-safe
          - scenario: embroider-optimized
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ci-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Test
        run: yarn ember try:one ${{ matrix.scenario }} --- ${{ matrix.command }}
